# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    left_gripper_controller:
      type: position_controllers/GripperActionController


    right_gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm_controller:
  ros__parameters:
    joints:
      - robl_joint_1
      - robl_joint_2
      - robl_joint_3
      - robl_joint_4
      - robl_joint_5
      - robl_joint_6
      - robl_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
right_arm_controller:
  ros__parameters:
    joints:
      - robr_joint_1
      - robr_joint_2
      - robr_joint_3
      - robr_joint_4
      - robr_joint_5
      - robr_joint_6
      - robr_joint_7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
left_gripper_controller:
  ros__parameters:
    joint: grpl_half_aperture_joint
right_gripper_controller:
  ros__parameters:
    joint: grpr_half_aperture_joint